
services :
   source :
      image: postgres:15
      ports:
         - "5432:5432"
      networks:
         - elt_network
      environment:
         POSTGRES_DB : source_db
         POSTGRES_USER : postgres
         POSTGRES_PASSWORD : secret
      volumes:
            - ./source_db_init/init.sql:/docker-entrypoint-initdb.d/init.sql

   destination :
      image: postgres:15
      ports:
         - "5433:5432" 
      networks:
         - elt_network
      environment:
         POSTGRES_DB : destination_db 
         POSTGRES_USER : postgres 
         POSTGRES_PASSWORD : secret 
   elt_script:
      build:
         context : .
         dockerfile: Dockerfile.elt_script
      command : [ 
         "python", 
         "elt_script.py"
      ]
      networks: 
         - elt_network 
      depends_on : 
         - source 
         - destination 
   dbt:
      image : ghcr.io/dbt-labs/dbt-postgres
      command :
         [
            "run",
            "--profiles-dir",
            "/root",
            "--project-dir",
            "/dbt"
         ]
      networks:
        - elt_network 
      volumes:
         - ./first_dbt:/dbt
         - "C:/Users/Admin/.dbt:/root" # profile configuration : a detail db connection
      depends_on:
         elt_script:
            condition: service_completed_successfully
      environment:
         DBT_PROFILE : first_dbt
         DBT_TARGET : dev

networks:
  elt_network:
   driver: bridge 


